fastlane_version '2.53.1'

platform :ios do
	desc 'Build the prod iOS application.'
	lane :prod do |options|
		match(type: 'appstore')
		increment_build_number_in_plist(
			 xcodeproj: './ApiDoc.xcodeproj',
			 target:"ApiDoc"
		)
		update_code_signing_settings(
	        use_automatic_signing: false,
	        path: "./ApiDoc.xcodeproj"
		)
		build_app(
			project: "./ApiDoc.xcodeproj",
			scheme: "ApiDoc",
			clean: true,
			export_method: "app-store"
        )
		pilot(skip_waiting_for_build_processing:true)
	end
end

